# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lr_app', '0002_auto_20180227_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_added', to='lr_app.User')),
                ('wishers', models.ManyToManyField(related_name='wish_joined', to='lr_app.User')),
            ],
        ),
    ]
