# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='action',
        ),
    ]
